name: art_space_artist
description: A new Flutter project.
publish_to: 'https://github.com/abdelstarMo66/art_space_artist'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^16.1.0
  sizer: ^2.0.15
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.1
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/alexandria/Alexandria-Black.ttf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 200
flutter_intl:
  enabled: true
